### ISSUE TITLE
Add the package.json to repo

### ISSUE THREAD

**Issue by waynemwashuma** [Oats-i/Oats-i#4]
The package.json is the binding point of all npm packages therefore i find it puzzling that it is missing here.

**Comment by waynemwashuma** [comment]
With regards to issue #3, I might be able to create a PR for building API documentation when it is included since i see that you already use jsdoc.

The package-lock.json can also be included if you require a CI/CD pipeline using github actions.

**Comment by Ian-Cornelius** [comment]
The package.json file is not here because that's supplied and maintained separately in our npm package distribution. You'll find it there if you want to have a look: https://www.npmjs.com/package/oats-i

A CI/CD pipeline is not required for this project at the moment. I'll be interested to see what you have as far as API documentation is concerned. Feel free to submit the PR and I'll have a look.

Cheers!

**Comment by waynemwashuma** [comment]
The API docs generation  requires the package.json to be in the repo as ill be installing an npm dev depedency for it.

**Comment by waynemwashuma** [comment]
Please refer to major npm packages,you will notice their package.json in the repo,so as to allow better collaboration using git.

**Comment by Ian-Cornelius** [comment]
What will be the output of the API docs you wish to produce? If it's from intellisense within the editor then that's being inferred directly at the moment, specifically from vscode which is my primary IDE. I'm assuming you want to extract it as a separate document in this case?

**Comment by waynemwashuma** [comment]
The documentation output will be HTML, can be added to your site.

**Comment by Ian-Cornelius** [comment]
I'm aware of what package.json will do. I haven't placed it here in the public source code because the package.json contains specific versioning, author, and collaborators information that needs to be maintained separately as that's what npm will use to publish the Oats~i package.

Maybe if you have an example of a major repo where they've maintained two separate versions of these files then you can share with me the link here and I'll have a look. But I'm avoiding scenarios where someone submits a PR only to change Oats~i's npm version or update collaborator lists, so that's why you can't find the file here.

Also, Oats~i itself currently has no other dependencies.

**Comment by Ian-Cornelius** [comment]
> The documentation output will be HTML, can be added to your site.

Then instead of adding a dependency and a new package.json, just generate the output from your end, fix it in a new folder/file, then make a PR. I'll see how that will be maintained as part of the whole project, maybe in a docs branch for now.

**Comment by waynemwashuma** [comment]
> where they've maintained two separate versions of these files.

My point is not maintaining two versions,but one which is inside the current repo.
If we go by your approach,i have to have my own separate package.json file.
In fact every collaborator will have their own!This is bad.
Source of truth should be in the github repo,not anybody's local clone!

I do not see your .gitignore but most likely ignores the package.json.

> I'm aware of what package.json will do. I haven't placed it here in the public source code because the package.json contains specific versioning, author, and collaborators information that needs to be maintained separately as that's what npm will use to publish the Oats~i package.

Thats where you come in as the maintainer.You can decide not to merge the request when reviewing the PR or ask for changes.

> Maybe if you have an example of a major repo

Examples of repos with this kind of set up:
 - https://github.com/mrdoob/three.js
 - https://github.com/BabylonJS/Babylon.js
 - https://github.com/vitejs/vite
 - https://github.com/rollup/rollup
 - https://github.com/waynemwashuma/chaos-engine (im the author of this one)
 - and many more(look up npm popular packages)

> Also, Oats~i itself currently has no other dependencies.

This will not be a dependency, but a **dev** dependency which automatically builds docs.


> Then instead of adding a dependency and **a new package.json**

Thats why im requesting the package.json be set here.So i can add the dev dependency there instead of creating a new package.json which might cause a merge conflict later.

**Comment by Ian-Cornelius** [comment]
The idea was not to have everyone hold their own version of package.json but rather to have more control over what is added there as far as the library's dependencies are concerned and overall npm publishing data. But I see your point regardless.

I'll provide the package.json here. Expect a merge about 12 hours from now (it's quite late where I am so I need to grab some rest).

Hopefully, that will now help you get started with the docs.

Cheers!

**Comment by waynemwashuma** [comment]
> The idea was not to have everyone hold their own version of package.json 

That was an unseen effect of the current architecture.

> I'll provide the package.json here. Expect a merge about 12 hours from now (it's quite late where I am so I need to grab some rest).
> 
> Hopefully, that will now help you get started with the docs.

Will do.

**Comment by Ian-Cornelius** [comment]
Hi Wayne,

The package.json file has been merged to the main branch. I believe you should be now set to create the docs as needed. If everything is okay now you can notify me and I'll close this issue.

Cheers!
